version: '3'
services:
 redis:
    image: redis
    volumes:
      - redis:/data
 app:
  build: .
  command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
  volumes:
   - .:/forecast
  ports:
   - "3000:3000"
  depends_on:
   - redis
volumes:
  redis: